/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TablaPeriodica;

import java.awt.Component;
import java.awt.Image;
import java.awt.Label;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Javith
 */
public class interfazTabla extends javax.swing.JFrame {

    private ImageIcon central = new ImageIcon("backgrond.jpg");

    /**
     * Creates new form interfazTabla
     */
    public interfazTabla() {
        initComponents();
        JButton[] arrBtn = new JButton[9];//arreglo de botones
        arrBtn[0] = this.btn1;
        Component[] component = this.getComponents();

        for (int i = 0; i < component.length; i++) {
            component[i].setEnabled(false);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AreaBotones = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn312 = new javax.swing.JButton();
        btn4534 = new javax.swing.JButton();
        btn5534 = new javax.swing.JButton();
        btn612 = new javax.swing.JButton();
        btn7323 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn48 = new javax.swing.JButton();
        btn49 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn51 = new javax.swing.JButton();
        btn52 = new javax.swing.JButton();
        btn53 = new javax.swing.JButton();
        btn54 = new javax.swing.JButton();
        btn55 = new javax.swing.JButton();
        btn56 = new javax.swing.JButton();
        btn111 = new javax.swing.JButton();
        btn58 = new javax.swing.JButton();
        btn59 = new javax.swing.JButton();
        btn60 = new javax.swing.JButton();
        btn61 = new javax.swing.JButton();
        btn112 = new javax.swing.JButton();
        btn63 = new javax.swing.JButton();
        btn64 = new javax.swing.JButton();
        btn65 = new javax.swing.JButton();
        btn66 = new javax.swing.JButton();
        btn113 = new javax.swing.JButton();
        btn68 = new javax.swing.JButton();
        btn69 = new javax.swing.JButton();
        btn70 = new javax.swing.JButton();
        btn71 = new javax.swing.JButton();
        btn114 = new javax.swing.JButton();
        btn73 = new javax.swing.JButton();
        btn74 = new javax.swing.JButton();
        btn75 = new javax.swing.JButton();
        btn76 = new javax.swing.JButton();
        btn115 = new javax.swing.JButton();
        btn78 = new javax.swing.JButton();
        btn79 = new javax.swing.JButton();
        btn80 = new javax.swing.JButton();
        btn81 = new javax.swing.JButton();
        btn116 = new javax.swing.JButton();
        btn83 = new javax.swing.JButton();
        btn84 = new javax.swing.JButton();
        btn85 = new javax.swing.JButton();
        btn117 = new javax.swing.JButton();
        btn87 = new javax.swing.JButton();
        btn88 = new javax.swing.JButton();
        btn118 = new javax.swing.JButton();
        btn90 = new javax.swing.JButton();
        btn91 = new javax.swing.JButton();
        btn92 = new javax.swing.JButton();
        btn93 = new javax.swing.JButton();
        btn94 = new javax.swing.JButton();
        btn09 = new javax.swing.JButton();
        btn08 = new javax.swing.JButton();
        btn07 = new javax.swing.JButton();
        btn06 = new javax.swing.JButton();
        btn05 = new javax.swing.JButton();
        btn119 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        etImagenCentral = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn120 = new javax.swing.JButton();
        btn121 = new javax.swing.JButton();
        btn122 = new javax.swing.JButton();
        btn123 = new javax.swing.JButton();
        btn124 = new javax.swing.JButton();
        btn125 = new javax.swing.JButton();
        btn126 = new javax.swing.JButton();
        btn127 = new javax.swing.JButton();
        btn128 = new javax.swing.JButton();
        btn129 = new javax.swing.JButton();
        btn130 = new javax.swing.JButton();
        btn131 = new javax.swing.JButton();
        btn132 = new javax.swing.JButton();
        btn133 = new javax.swing.JButton();
        btn134 = new javax.swing.JButton();
        btn135 = new javax.swing.JButton();
        btn136 = new javax.swing.JButton();
        btn137 = new javax.swing.JButton();
        btn138 = new javax.swing.JButton();
        btn139 = new javax.swing.JButton();
        btn140 = new javax.swing.JButton();
        btn141 = new javax.swing.JButton();
        btn142 = new javax.swing.JButton();
        btn143 = new javax.swing.JButton();
        btn144 = new javax.swing.JButton();
        btn145 = new javax.swing.JButton();
        btn146 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        AreaBotones.setBackground(new java.awt.Color(204, 255, 255));
        AreaBotones.setLayout(null);

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Elementos/H.gif"))); // NOI18N
        btn1.setBorder(new javax.swing.border.MatteBorder(null));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        AreaBotones.add(btn1);
        btn1.setBounds(40, 100, 42, 41);
        AreaBotones.add(btn2);
        btn2.setBounds(890, 100, 42, 41);
        AreaBotones.add(btn3);
        btn3.setBounds(40, 150, 42, 41);
        AreaBotones.add(btn4);
        btn4.setBounds(90, 150, 42, 41);
        AreaBotones.add(btn312);
        btn312.setBounds(40, 200, 42, 41);
        AreaBotones.add(btn4534);
        btn4534.setBounds(40, 250, 42, 41);
        AreaBotones.add(btn5534);
        btn5534.setBounds(40, 300, 42, 41);
        AreaBotones.add(btn612);
        btn612.setBounds(40, 350, 42, 41);
        AreaBotones.add(btn7323);
        btn7323.setBounds(40, 400, 42, 41);
        AreaBotones.add(btn9);
        btn9.setBounds(90, 200, 42, 41);
        AreaBotones.add(btn10);
        btn10.setBounds(90, 250, 42, 41);
        AreaBotones.add(btn11);
        btn11.setBounds(90, 300, 42, 41);
        AreaBotones.add(btn12);
        btn12.setBounds(90, 350, 42, 41);
        AreaBotones.add(btn13);
        btn13.setBounds(90, 400, 42, 41);
        AreaBotones.add(btn14);
        btn14.setBounds(140, 200, 42, 41);
        AreaBotones.add(btn15);
        btn15.setBounds(140, 250, 42, 41);
        AreaBotones.add(btn16);
        btn16.setBounds(140, 300, 42, 41);
        AreaBotones.add(btn17);
        btn17.setBounds(140, 350, 42, 41);
        AreaBotones.add(btn18);
        btn18.setBounds(140, 400, 42, 41);
        AreaBotones.add(btn19);
        btn19.setBounds(190, 200, 42, 41);
        AreaBotones.add(btn20);
        btn20.setBounds(190, 250, 42, 41);
        AreaBotones.add(btn21);
        btn21.setBounds(190, 300, 42, 41);
        AreaBotones.add(btn22);
        btn22.setBounds(190, 350, 42, 41);
        AreaBotones.add(btn23);
        btn23.setBounds(190, 400, 42, 41);
        AreaBotones.add(btn24);
        btn24.setBounds(240, 200, 42, 41);
        AreaBotones.add(btn25);
        btn25.setBounds(240, 250, 42, 41);
        AreaBotones.add(btn26);
        btn26.setBounds(240, 300, 42, 41);
        AreaBotones.add(btn27);
        btn27.setBounds(240, 350, 42, 41);
        AreaBotones.add(btn28);
        btn28.setBounds(240, 400, 42, 41);
        AreaBotones.add(btn29);
        btn29.setBounds(290, 200, 42, 41);
        AreaBotones.add(btn30);
        btn30.setBounds(290, 250, 42, 41);
        AreaBotones.add(btn31);
        btn31.setBounds(290, 300, 42, 41);
        AreaBotones.add(btn32);
        btn32.setBounds(290, 350, 42, 41);
        AreaBotones.add(btn33);
        btn33.setBounds(290, 400, 42, 41);
        AreaBotones.add(btn34);
        btn34.setBounds(340, 350, 42, 41);
        AreaBotones.add(btn35);
        btn35.setBounds(340, 400, 42, 41);
        AreaBotones.add(btn36);
        btn36.setBounds(340, 250, 42, 41);
        AreaBotones.add(btn37);
        btn37.setBounds(340, 300, 42, 41);
        AreaBotones.add(btn38);
        btn38.setBounds(340, 200, 42, 41);
        AreaBotones.add(btn39);
        btn39.setBounds(390, 350, 42, 41);
        AreaBotones.add(btn40);
        btn40.setBounds(390, 400, 42, 41);
        AreaBotones.add(btn41);
        btn41.setBounds(390, 250, 42, 41);
        AreaBotones.add(btn42);
        btn42.setBounds(390, 300, 42, 41);
        AreaBotones.add(btn43);
        btn43.setBounds(390, 200, 42, 41);
        AreaBotones.add(btn44);
        btn44.setBounds(440, 400, 42, 41);
        AreaBotones.add(btn45);
        btn45.setBounds(440, 250, 42, 41);
        AreaBotones.add(btn46);
        btn46.setBounds(440, 350, 42, 41);
        AreaBotones.add(btn47);
        btn47.setBounds(440, 300, 42, 41);
        AreaBotones.add(btn48);
        btn48.setBounds(440, 200, 42, 41);
        AreaBotones.add(btn49);
        btn49.setBounds(490, 250, 42, 41);
        AreaBotones.add(btn50);
        btn50.setBounds(490, 300, 42, 41);
        AreaBotones.add(btn51);
        btn51.setBounds(490, 200, 42, 41);
        AreaBotones.add(btn52);
        btn52.setBounds(490, 400, 42, 41);
        AreaBotones.add(btn53);
        btn53.setBounds(490, 350, 42, 41);
        AreaBotones.add(btn54);
        btn54.setBounds(540, 250, 42, 41);
        AreaBotones.add(btn55);
        btn55.setBounds(540, 300, 42, 41);
        AreaBotones.add(btn56);
        btn56.setBounds(540, 200, 42, 41);
        AreaBotones.add(btn111);
        btn111.setBounds(540, 400, 42, 41);
        AreaBotones.add(btn58);
        btn58.setBounds(540, 350, 42, 41);
        AreaBotones.add(btn59);
        btn59.setBounds(590, 250, 42, 41);
        AreaBotones.add(btn60);
        btn60.setBounds(590, 300, 42, 41);
        AreaBotones.add(btn61);
        btn61.setBounds(590, 200, 42, 41);
        AreaBotones.add(btn112);
        btn112.setBounds(590, 400, 42, 41);
        AreaBotones.add(btn63);
        btn63.setBounds(590, 350, 42, 41);
        AreaBotones.add(btn64);
        btn64.setBounds(640, 250, 42, 41);
        AreaBotones.add(btn65);
        btn65.setBounds(640, 300, 42, 41);
        AreaBotones.add(btn66);
        btn66.setBounds(640, 200, 42, 41);
        AreaBotones.add(btn113);
        btn113.setBounds(640, 400, 42, 41);
        AreaBotones.add(btn68);
        btn68.setBounds(640, 350, 42, 41);
        AreaBotones.add(btn69);
        btn69.setBounds(690, 250, 42, 41);
        AreaBotones.add(btn70);
        btn70.setBounds(690, 300, 42, 41);
        AreaBotones.add(btn71);
        btn71.setBounds(690, 200, 42, 41);
        AreaBotones.add(btn114);
        btn114.setBounds(690, 400, 42, 41);
        AreaBotones.add(btn73);
        btn73.setBounds(690, 350, 42, 41);
        AreaBotones.add(btn74);
        btn74.setBounds(740, 250, 42, 41);
        AreaBotones.add(btn75);
        btn75.setBounds(740, 300, 42, 41);
        AreaBotones.add(btn76);
        btn76.setBounds(740, 200, 42, 41);
        AreaBotones.add(btn115);
        btn115.setBounds(740, 400, 42, 41);
        AreaBotones.add(btn78);
        btn78.setBounds(740, 350, 42, 41);
        AreaBotones.add(btn79);
        btn79.setBounds(790, 250, 42, 41);
        AreaBotones.add(btn80);
        btn80.setBounds(790, 300, 42, 41);
        AreaBotones.add(btn81);
        btn81.setBounds(790, 200, 42, 41);
        AreaBotones.add(btn116);
        btn116.setBounds(790, 400, 42, 41);

        btn83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn83ActionPerformed(evt);
            }
        });
        AreaBotones.add(btn83);
        btn83.setBounds(790, 350, 42, 41);
        AreaBotones.add(btn84);
        btn84.setBounds(840, 200, 42, 41);
        AreaBotones.add(btn85);
        btn85.setBounds(840, 250, 42, 41);
        AreaBotones.add(btn117);
        btn117.setBounds(840, 400, 42, 41);
        AreaBotones.add(btn87);
        btn87.setBounds(840, 300, 42, 41);
        AreaBotones.add(btn88);
        btn88.setBounds(840, 350, 42, 41);
        AreaBotones.add(btn118);
        btn118.setBounds(160, 470, 42, 41);

        btn90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn90ActionPerformed(evt);
            }
        });
        AreaBotones.add(btn90);
        btn90.setBounds(890, 200, 42, 41);
        AreaBotones.add(btn91);
        btn91.setBounds(890, 300, 42, 41);
        AreaBotones.add(btn92);
        btn92.setBounds(890, 250, 42, 41);
        AreaBotones.add(btn93);
        btn93.setBounds(890, 350, 42, 41);
        AreaBotones.add(btn94);
        btn94.setBounds(890, 150, 42, 41);
        AreaBotones.add(btn09);
        btn09.setBounds(840, 150, 42, 41);
        AreaBotones.add(btn08);
        btn08.setBounds(790, 150, 42, 41);
        AreaBotones.add(btn07);
        btn07.setBounds(740, 150, 42, 41);
        AreaBotones.add(btn06);
        btn06.setBounds(690, 150, 42, 41);
        AreaBotones.add(btn05);
        btn05.setBounds(640, 150, 42, 41);
        AreaBotones.add(btn119);
        btn119.setBounds(890, 400, 42, 41);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("3");
        AreaBotones.add(jLabel1);
        jLabel1.setBounds(20, 210, 10, 22);
        AreaBotones.add(etImagenCentral);
        etImagenCentral.setBounds(290, 10, 260, 130);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2");
        AreaBotones.add(jLabel2);
        jLabel2.setBounds(100, 120, 10, 22);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("4");
        AreaBotones.add(jLabel3);
        jLabel3.setBounds(20, 260, 10, 22);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("5");
        AreaBotones.add(jLabel4);
        jLabel4.setBounds(20, 310, 10, 22);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("6");
        AreaBotones.add(jLabel5);
        jLabel5.setBounds(20, 360, 10, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("7");
        AreaBotones.add(jLabel6);
        jLabel6.setBounds(20, 410, 10, 22);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("2");
        AreaBotones.add(jLabel7);
        jLabel7.setBounds(20, 160, 10, 22);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("1");
        AreaBotones.add(jLabel8);
        jLabel8.setBounds(20, 110, 10, 22);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("3");
        AreaBotones.add(jLabel9);
        jLabel9.setBounds(150, 170, 10, 22);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("4");
        AreaBotones.add(jLabel10);
        jLabel10.setBounds(200, 170, 10, 22);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("5");
        AreaBotones.add(jLabel11);
        jLabel11.setBounds(250, 170, 10, 22);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("6");
        AreaBotones.add(jLabel12);
        jLabel12.setBounds(300, 170, 10, 22);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("7");
        AreaBotones.add(jLabel13);
        jLabel13.setBounds(350, 170, 10, 22);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("9");
        AreaBotones.add(jLabel14);
        jLabel14.setBounds(450, 170, 10, 22);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("11");
        AreaBotones.add(jLabel15);
        jLabel15.setBounds(550, 170, 20, 22);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("8");
        AreaBotones.add(jLabel16);
        jLabel16.setBounds(400, 170, 10, 22);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("12");
        AreaBotones.add(jLabel17);
        jLabel17.setBounds(600, 170, 20, 22);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("13");
        AreaBotones.add(jLabel18);
        jLabel18.setBounds(650, 120, 20, 22);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("14");
        AreaBotones.add(jLabel19);
        jLabel19.setBounds(700, 120, 20, 22);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("15");
        AreaBotones.add(jLabel20);
        jLabel20.setBounds(750, 120, 20, 22);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("16");
        AreaBotones.add(jLabel21);
        jLabel21.setBounds(800, 120, 20, 22);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("1");
        AreaBotones.add(jLabel22);
        jLabel22.setBounds(50, 70, 20, 22);

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("10");
        AreaBotones.add(jLabel23);
        jLabel23.setBounds(500, 170, 20, 22);

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("17");
        AreaBotones.add(jLabel24);
        jLabel24.setBounds(850, 120, 20, 22);

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("18");
        AreaBotones.add(jLabel25);
        jLabel25.setBounds(900, 70, 20, 22);

        btn120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn120ActionPerformed(evt);
            }
        });
        AreaBotones.add(btn120);
        btn120.setBounds(210, 470, 42, 41);
        AreaBotones.add(btn121);
        btn121.setBounds(260, 470, 42, 41);
        AreaBotones.add(btn122);
        btn122.setBounds(310, 470, 42, 41);
        AreaBotones.add(btn123);
        btn123.setBounds(360, 470, 42, 41);
        AreaBotones.add(btn124);
        btn124.setBounds(410, 470, 42, 41);
        AreaBotones.add(btn125);
        btn125.setBounds(460, 470, 42, 41);
        AreaBotones.add(btn126);
        btn126.setBounds(510, 470, 42, 41);
        AreaBotones.add(btn127);
        btn127.setBounds(560, 470, 42, 41);
        AreaBotones.add(btn128);
        btn128.setBounds(610, 470, 42, 41);
        AreaBotones.add(btn129);
        btn129.setBounds(660, 470, 42, 41);
        AreaBotones.add(btn130);
        btn130.setBounds(710, 470, 42, 41);
        AreaBotones.add(btn131);
        btn131.setBounds(760, 470, 42, 41);
        AreaBotones.add(btn132);
        btn132.setBounds(810, 470, 42, 41);
        AreaBotones.add(btn133);
        btn133.setBounds(260, 520, 42, 41);
        AreaBotones.add(btn134);
        btn134.setBounds(410, 520, 42, 41);
        AreaBotones.add(btn135);
        btn135.setBounds(510, 520, 42, 41);
        AreaBotones.add(btn136);
        btn136.setBounds(660, 520, 42, 41);
        AreaBotones.add(btn137);
        btn137.setBounds(460, 520, 42, 41);
        AreaBotones.add(btn138);
        btn138.setBounds(710, 520, 42, 41);
        AreaBotones.add(btn139);
        btn139.setBounds(560, 520, 42, 41);

        btn140.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn140ActionPerformed(evt);
            }
        });
        AreaBotones.add(btn140);
        btn140.setBounds(210, 520, 42, 41);
        AreaBotones.add(btn141);
        btn141.setBounds(810, 520, 42, 41);
        AreaBotones.add(btn142);
        btn142.setBounds(310, 520, 42, 41);
        AreaBotones.add(btn143);
        btn143.setBounds(360, 520, 42, 41);
        AreaBotones.add(btn144);
        btn144.setBounds(610, 520, 42, 41);
        AreaBotones.add(btn145);
        btn145.setBounds(760, 520, 42, 41);
        AreaBotones.add(btn146);
        btn146.setBounds(160, 520, 42, 41);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/367969_1920_1080.jpg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(1920, 1250));
        Fondo.setMinimumSize(new java.awt.Dimension(1920, 1250));
        Fondo.setOpaque(true);
        AreaBotones.add(Fondo);
        Fondo.setBounds(0, 0, 960, 650);

        jScrollPane1.setViewportView(AreaBotones);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 950, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn90ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn90ActionPerformed

    private void btn83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn83ActionPerformed

    private void btn120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn120ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn120ActionPerformed

    private void btn140ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn140ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn140ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazTabla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaBotones;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btn05;
    private javax.swing.JButton btn06;
    private javax.swing.JButton btn07;
    private javax.swing.JButton btn08;
    private javax.swing.JButton btn09;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn111;
    private javax.swing.JButton btn112;
    private javax.swing.JButton btn113;
    private javax.swing.JButton btn114;
    private javax.swing.JButton btn115;
    private javax.swing.JButton btn116;
    private javax.swing.JButton btn117;
    private javax.swing.JButton btn118;
    private javax.swing.JButton btn119;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn120;
    private javax.swing.JButton btn121;
    private javax.swing.JButton btn122;
    private javax.swing.JButton btn123;
    private javax.swing.JButton btn124;
    private javax.swing.JButton btn125;
    private javax.swing.JButton btn126;
    private javax.swing.JButton btn127;
    private javax.swing.JButton btn128;
    private javax.swing.JButton btn129;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn130;
    private javax.swing.JButton btn131;
    private javax.swing.JButton btn132;
    private javax.swing.JButton btn133;
    private javax.swing.JButton btn134;
    private javax.swing.JButton btn135;
    private javax.swing.JButton btn136;
    private javax.swing.JButton btn137;
    private javax.swing.JButton btn138;
    private javax.swing.JButton btn139;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn140;
    private javax.swing.JButton btn141;
    private javax.swing.JButton btn142;
    private javax.swing.JButton btn143;
    private javax.swing.JButton btn144;
    private javax.swing.JButton btn145;
    private javax.swing.JButton btn146;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn312;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn4534;
    private javax.swing.JButton btn46;
    private javax.swing.JButton btn47;
    private javax.swing.JButton btn48;
    private javax.swing.JButton btn49;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn51;
    private javax.swing.JButton btn52;
    private javax.swing.JButton btn53;
    private javax.swing.JButton btn54;
    private javax.swing.JButton btn55;
    private javax.swing.JButton btn5534;
    private javax.swing.JButton btn56;
    private javax.swing.JButton btn58;
    private javax.swing.JButton btn59;
    private javax.swing.JButton btn60;
    private javax.swing.JButton btn61;
    private javax.swing.JButton btn612;
    private javax.swing.JButton btn63;
    private javax.swing.JButton btn64;
    private javax.swing.JButton btn65;
    private javax.swing.JButton btn66;
    private javax.swing.JButton btn68;
    private javax.swing.JButton btn69;
    private javax.swing.JButton btn70;
    private javax.swing.JButton btn71;
    private javax.swing.JButton btn73;
    private javax.swing.JButton btn7323;
    private javax.swing.JButton btn74;
    private javax.swing.JButton btn75;
    private javax.swing.JButton btn76;
    private javax.swing.JButton btn78;
    private javax.swing.JButton btn79;
    private javax.swing.JButton btn80;
    private javax.swing.JButton btn81;
    private javax.swing.JButton btn83;
    private javax.swing.JButton btn84;
    private javax.swing.JButton btn85;
    private javax.swing.JButton btn87;
    private javax.swing.JButton btn88;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btn90;
    private javax.swing.JButton btn91;
    private javax.swing.JButton btn92;
    private javax.swing.JButton btn93;
    private javax.swing.JButton btn94;
    private javax.swing.JLabel etImagenCentral;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
